version: '3.3'
services:
  app:
    image: app
    build: .
    ports: 
      - target: 5000
        published: 80
    
  jenkins:
    image: jenkins/jenkins:latest
    ports: 
      - target: 8080
        published: 8080
    volumes: 
      - type: volume
        source: jenkins-home
        target: "/var/jenkiins_home"
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
volumes:
    jenkins-home: 